apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-field-slicer-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: linode-block-storage-retain
