#!/bin/bash
# This file was automatically generated by jinjaroot. Do not edit directly. See the .jinjaroot dir.


set -ex

yarn install
yarn build
rm -rf src/python/field_slicer/build
cp -r build src/python/field_slicer/
